---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by martin.
--- DateTime: 2020/9/20 20:38
---

local function add(l, r)
    return l + r
end

--local r = add(11, 03)
--local a = r + 1