---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by martin.
--- DateTime: 2020/9/28 16:24
---
local x, xx = 88, 11
local function foo()
    local y = x
    local yy = xx
    return y, yy
end
local a, b = foo()
a = a + b
