---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by martin.
--- DateTime: 2020/9/20 20:38
---

local function add(l, r)
    return l + r
end

--local function nop()
--    return 1
--end

local r = add(11, 03)
--nop()
return 11,03,r